### ISSUE TITLE
細かい修正 8/22

### ISSUE THREAD

**Issue by jsankw** [toshimin/skill-sample-nodejs-simple-hello-world#2]
- 開発アカウント権限を持っているかどうかは最初にチェックしたほうがいいかもしれません。途中までやって、テストしてみたら購入できなくてまた違うアカウントでテストしないといけなくなってしまいます。（例えば今のアカウントでalexa.amazon.co.jpにログインしてalexa.amazon.comにリダイレクトされるか、1-Click設定はされているか）

 [https://github.com/toshimin/skill-sample-nodejs-simple-hello-world/blob/master/instructions/1-1-setup-using-alexa-hosted.md](https://github.com/toshimin/skill-sample-nodejs-simple-hello-world/blob/master/instructions/1-1-setup-using-alexa-hosted.md) 
### スキル内商品の登録

* 9番目のリンクを念のためにJPにつけたほうがいいかもしれません：
	*  [https://developer.amazon.com/ja/docs/in-skill-purchase/create-isp-dev-console.html#tax-category](https://developer.amazon.com/ja/docs/in-skill-purchase/create-isp-dev-console.html#tax-category) 
* 12番目に「スキルにリンク」をちゃんと押下してもらったほうがいいかもしれません (Subscriptionのところも同様)
 
### バックエンドコードの作成

* 6-9番では各ファイルを「保存」しないといけないので、念のためindex.jsを更新したら保存してもらったほうがいいかもしれません
 
 [https://github.com/toshimin/skill-sample-nodejs-simple-hello-world/blob/master/instructions/2-test.md](https://github.com/toshimin/skill-sample-nodejs-simple-hello-world/blob/master/instructions/2-test.md)

**Comment by toshimin** [comment]
対応済み
